version: "3.8"
services:
  webapp:
    build: ./docker  
    image: django/demo
    container_name: django-demo
    hostname: django-dev-demo
    volumes:
       - ./app:/app
    command: /app/scripts/startup.sh
