version: "3.8"
services:
  webapp:
    build: ./docker  
    image: django/gql-scaffold
    container_name: scaffold
    hostname: dev
    volumes:
       - ./app:/app
    command: /app/scripts/startup.sh
